# Generated by Django 5.2.3 on 2025-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_anonymous_id_post_image_post_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
