# Generated by Django 5.2.3 on 2025-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anonymous_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
